---
- name: Include Vars
  include_vars: config.yml

- name: Create symbolic link to Apps locally
  ansible.builtin.file:
    src: "{{ host_path }}/App/"
    dest: "{{ host_path }}/ansible/roles/webApp/files/App"
    state: link
  delegate_to: localhost

- name: Install Python3
  apt:
    name: "{{ item }}"
    state: present
    cache_valid_time: 3600
  loop:
    - python3
    - python3-pip
    - default-libmysqlclient-dev
  become: yes

- name: Make Dragownd Directory
  ansible.builtin.file:
    path: "{{ path }}"
    state: directory

- name: Copy Config to Server
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: yes
  loop:
    - { src: App/, dest: "{{ path }}/App" }
    - { src: "{{ host_path }}/installer/requirements.txt", dest: "{{ path }}/requirements.txt" }

- name: Install Python3 Dependencies
  pip:
    requirements: "{{ path }}/requirements.txt"

- name: Copy Template Locally
  copy:
    src: "{{ host_path }}/ansible/roles/webApp/files/App/connect.py"
    dest: "{{ host_path }}/ansible/roles/webApp/templates/connect.j2"
  delegate_to: localhost

- name: Populate Config
  template:
    src: connect.j2
    dest: "{{ path }}/App/connect.py"


- name: Install Flask to Ansible Path
  ansible.builtin.shell: 
    chdir: "{{ path }}/App"
    cmd: pip3 install flask
  args:
    executable: /bin/bash

- name: Start Flask
  ansible.builtin.shell: 
    chdir: "{{ path }}/App"
    cmd: screen -R flask -L -d -m ./runflask.sh
  args:
    executable: /bin/bash