---
- name: Include Vars (free-form)
  include_vars: config.yml

- name: Write hostname to vars
  lineinfile:
    path: "{{ host_path }}/ansible/config.yml"
    line: "db_host: {{ inventory_hostname }}"
    insertafter: EOF
  delegate_to: localhost

- name: Include Vars Again
  include_vars: config.yml

- name: Create symbolic link to installer locally
  ansible.builtin.file:
    src: "{{ host_path }}/installer/"
    dest: "{{ host_path }}/ansible/roles/db/files/installer"
    state: link
  delegate_to: localhost

- name: Install mysql
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  loop:
    - mariadb-server
    - python3-pip

- name: Install pymysql
  pip:
    name: pymysql

- name: Install pymysql as root
  pip:
    name: pymysql
  become: yes

- name: Copy Template Locally
  copy:
    src: "{{ host_path }}/ansible/roles/db/files/installer/"
    dest: "{{ path }}/installer"

- name: Start the MySQL Service
  service:  
    name=mysql 
    state=started
    enabled=yes
  become: yes

- name: Create root db user
  community.mysql.mysql_user:
    check_implicit_admin: yes
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: root
    password: "{{ mysql_root_password }}"
    priv: '*.*:ALL,GRANT'
    state: present
  become: yes

- name: Create dragownd db
  community.mysql.mysql_db:
    check_implicit_admin: yes
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: dragownd
    state: present

- name: Create dragownd db user
  community.mysql.mysql_user:
    check_implicit_admin: yes
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: dragownd
    password: "{{ password }}"
    priv: 'dragownd.*:ALL,GRANT'
    state: present

- name: import tables and views
  ansible.builtin.shell:
    cmd: mysql -uroot -p"{{ mysql_root_password }}"< "{{ path }}/installer/install.mysql"
