---
- hosts: all
  vars:
    ssh_key: ~/.ssh/id_rsa
    path: ~/dragownd
    mysql_root_password:
    password
    host_path
    range
- name: symbolic link to Apps 
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: symbolic link
    ansible.builtin.shell:
      cmd: ln -s "{{ host_path }}/App" "{{ host_path }}/ansible/roles/webApp/files/App"

- name: symbolic link to Install 
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: symbolic link
    ansible.builtin.shell:
      cmd: ln -s "{{ host_path }}/installer" "{{ host_path }}/ansible/roles/db/files/installer"

- name: symbolic link to nmap 
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: symbolic link
    ansible.builtin.shell:
      cmd: ln -s "{{ host_path }}/nmap" "{{ host_path }}/ansible/roles/scanner/files/nmap"
