---
- name: Include Vars (free-form)
  include_vars: 
    file: config.yml

- name: Create symbolic link to nmap locally
  ansible.builtin.file:
    src: "{{ host_path }}/nmap/"
    dest: "{{ host_path }}/ansible/roles/scanner/files/nmap"
    state: link
  delegate_to: localhost

- name: Install nmap
  apt:
    name: "nmap"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Copy nmap Files to Server
  copy:
    src: "{{ host_path }}/nmap/"
    dest: "{{ path }}/nmap"

- name: Install Python3
  apt:
    name: "{{ item }}"
    state: present
    cache_valid_time: 3600
  loop:
    - python3
    - python3-pip
    - default-libmysqlclient-dev
  become: yes

- name: Copy Requirements to Server
  copy:
    src: "{{ host_path }}/installer/requirements.txt"
    dest: "{{ path }}/requirements.txt"
    force: yes

- name: Install Python3 Dependencies
  pip:
    requirements: "{{ path }}/requirements.txt"

- name: Copy nmap Templates Locally
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  delegate_to: localhost
  loop:
    - { src: "{{ host_path }}/ansible/roles/scanner/files/nmap/nmap_recon.py", dest: "{{ host_path }}/ansible/roles/scanner/templates/nmap_recon.j2" }
    - { src: "{{ host_path }}/ansible/roles/scanner/files/nmap/ranges.txt", dest: "{{ host_path }}/ansible/roles/scanner/templates/ranges.j2" }

- name: Config with Templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
      - { src: "{{ host_path }}/ansible/roles/scanner/templates/nmap_recon.j2", dest: "{{ path }}/nmap/nmap_recon.py" }
      - { src: "{{ host_path }}/ansible/roles/scanner/templates/ranges.j2", dest: "{{ path }}/nmap/ranges.txt" }


- name: Create Scanner cronjob
  ansible.builtin.cron:
    name: dragownd daily nmap
    special_time: daily
    job: python3 "{{ path }}/nmap/nmap_recon.py" > "{{ path }}/nmap/crontab.log"
  become: yes

- name: Run nmap Script
  ansible.builtin.shell:
    chdir: "{{ path }}/nmap/"
    cmd: screen -S nmap -L -d -m python3 "{{ path }}/nmap/nmap_recon.py" && sleep 1